---
title: "Paper Figures"
output: html_document
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "figures/", dpi = 360)
```

```{r include=FALSE}
library(extrafont)
# font_import()
loadfonts(dev = "win")
```

```{r include = FALSE}
if (!dir.exists("publication_figures")){dir.create("publication_figures")}
```

```{r include=FALSE}
# read the package manually
#source("analysis/read_microxanox.R")
library(microxanox)
library(tidyverse)
library(patchwork)
library(ggpubr)

# globals
textsize <- 8
tagsize <- 10
margin.r <- 3
margin.l <- 3
margin.t <- 3


# set the theme such that all figures look the same
# theme_set(
my_theme <-  theme(text = element_text(size = textsize),
        axis.title = element_blank(),
        title = element_blank(),
        # axis.ticks.x = element_blank(),
        # axis.ticks.y = element_blank(),
        # axis.text = element_text(size = 7, family = "Calibri"),
        # axis.title.x = element_text(
        #   size = 8,
        #   margin = margin(t = 3)
        # ),
        axis.title.y = element_blank(),
        axis.title.x.top = element_blank(),
        # axis.text.y = element_blank(),
        panel.background = element_blank(),
        axis.line.x = element_line(arrow = grid::arrow(length = unit(0.2, "cm"), 
                                                      ends = "both")),
        axis.line.y = element_line(arrow = grid::arrow(length = unit(0.2, "cm"),
                                                       ends = "last")),
        plot.tag = element_text(size = tagsize, face = "bold", margin = margin(0, 3, -5, -10)),
        legend.position = "bottom",
        legend.direction = 'horizontal'
        ) 
#
```



### Figure 1

```{r figure_1cd_revised, fig.height=7, fig.width=7}
# point to directory from project
wd <- "data/bush-sim"
# figure 1c, d: asymmetry in magnitudes in bush simulation
bush_res <- readRDS(file.path(wd, "simulation_bush_temporal.RDS"))

fig_1a <- ggplot() + theme(panel.background = element_blank()) + 
  labs(x = "Environmental driver", y = "Concentration") + 
  my_theme + 
  theme(axis.title.y = element_text(size = textsize, margin = margin(t = 0, r = margin.r)))

fig_1c <- plot_trajectory_symmetry_compact(res = bush_res, typ = "substrate") + 
  labs(y = expression(Log[10](Concentration)~"[μM]"), x = expression(Log[10](Oxygen~Diffusivity)~"["*hr^-1*"]")) +
  my_theme +
  theme(axis.title.y = element_text(size = textsize, margin = margin(r=margin.r)), 
        axis.title.x = element_text(size = textsize, margin = margin(t=margin.t)))

fig_1b <- fig_1d <- ggplot() + my_theme + theme(axis.line.x = element_blank(), axis.line.y = element_blank())

wrap_plots(fig_1a, fig_1b, fig_1c, fig_1d) +
  plot_layout(ncol = 2, guide = "collect") +
  guides(color = guide_legend(position = "bottom")) +
  plot_annotation(tag_levels = "a") &
  theme(legend.position = "bottom")
```


### Figure 3

```{r figure_3, eval = FALSE, echo = FALSE, fig.width=6, fig.height = 6}

# figure 3: dynamics
dyn_res <- readRDS(file.path("data", "symmetric-sim" , "simulation_time_dynamics_symmetric.RDS" ))
# calculate starting of time series
starting <- which(dyn_res$result$aO == 0)[1]
# recode for proper legends

df3 <- dyn_res$result %>% 
  # slice(starting:nrow(.)) %>% 
  dplyr::select(c(O, aO, aS, time, SR, P)) %>%
  mutate_at(c("O", "SR", "P"), log10) %>%
  gather(key = species, value = concentration, -time) %>%
  mutate(panel = ifelse(species %in% c("O", "SR"), "substrates",
                        ifelse(species %in% c("aO", "aS"), "diffusivities", 
                              "nutrient"))) %>% 
  mutate(species_plot = recode(species, 
                                O = "Oxygen", 
                                SR = "Sulfide",
                                aO = "Oxygen Diffusivity",
                                aS = "Sulfide Diffusisivity",
                                P = "Phosphate"
                               ))

fig3a<- ggplot(data = df3 %>% filter(panel == "diffusivities"), 
               mapping = aes(x = time, y = concentration, color = species_plot)) + 
          labs(x = "", y = expression(Log[10](Diffusivity)~"["*hr^-1*"]")) +
          geom_path(linetype = "dashed") + 
          scale_color_manual(values = c("#e85050", "#5da1df")) +
          coord_fixed() +
          theme(axis.title.x = element_blank())

fig3b <- ggplot(data = df3 %>% filter(panel == "substrates"), 
                mapping = aes(x = time, y= concentration, color = species_plot)) +
        geom_step()  +
        labs(x = "", y = expression(Log[10](Concentration)~"[μM]")) + # [μM]
        scale_color_manual(values = c("#e85050", "#5da1df")) +
        coord_fixed() +
        theme(axis.title.x = element_blank())

fig3c <- ggplot(data = df3 %>% filter(panel == "nutrient"),
                mapping = aes(x = time, y = concentration, color = species_plot)) +
            geom_step() +
        labs(x  = "Time [hr]", y = expression(Log[10](Concentration)~"[μM]")) +
        scale_color_manual(values = c("#674ea7")) + 
        coord_fixed() +
        theme(axis.title.x = element_text(size = textsize,
                                          margin = margin(t=10)))

wrap_plots(fig3a, fig3b, fig3c) + 
  plot_layout(ncol = 1, guide = "collect") +
  plot_annotation(tag_levels = "a") & 
  my_theme & 
  theme(axis.line.x = element_line(arrow = grid::arrow(length = unit(0.2, "cm"),
                                                      ends = "last")), 
        axis.title.y = element_text(size = textsize, margin = margin(t = 0, r = 3))
        )
# todo: y axis labels, x axis label
```

### Figure 4

```{r figure_4_revised, echo = FALSE, fig.width = 3.5, fig.height=10.5}
wd <- "data"

# figure 4 a) 
# symmetric case
sym_res <- readRDS(file.path("data", "asymmetric-sim", "stressor-asym", "simulation_asymmetric_stressor.asym1.RDS"))
fig_4a <- plot_trajectory_symmetry_compact(res = sym_res, typ = "substrate") + 
  labs(y = expression(Log[10](Concentration)~"[μM]")) + 
  my_theme +
  theme(axis.title.x.top = element_text(size = textsize, margin = margin(b = margin.t)), 
        axis.title.y = element_text(size = textsize, margin = margin(r = margin.r)))

# trait asym
asym_res_trait <- readRDS(file.path("data","asymmetric-sim", "trait-asym", "simulation_asymmetric_hOSB60.RDS"))
fig_4b <- plot_trajectory_symmetry_compact(res = asym_res_trait, typ = "substrate") +
  labs(y = expression(Log[10](Concentration)~"[μM]")) +
  my_theme +
  theme(axis.title.y = element_text(size = textsize, margin = margin(r = margin.r)))

# stressor asym
asym_res_stressor <- readRDS(file.path("data", "asymmetric-sim", "stressor-asym", "simulation_asymmetric_stressor.asym0.6.RDS"))
fig_4c <- plot_trajectory_symmetry_compact(res = asym_res_stressor, typ = "substrate") +
  labs(y = expression(Log[10](Concentration)~"[μM]")) +
  scale_y_continuous(breaks = c(0, 25, 50, 75, 100)) +
  my_theme +
  theme(axis.title.x = element_text(size = textsize, margin = margin(t=margin.t)),
        axis.title.y = element_text(size = textsize, margin = margin(r = margin.r)))

# 
wrap_plots(fig_4a, fig_4b, fig_4c) +
  plot_layout(ncol = 1, guides = "collect") +
  plot_annotation(tag_levels = 'a') &
  theme(plot.tag = element_text(margin = margin(0,0,-10,0)),
        legend.position = "bottom")

```


### Figure 5

```{r figure_5, echo = FALSE,  fig.width = 7, fig.height=7}
source("analysis/asymmetric_response_plotting.R")

plist_h0SB <- plot_asymmetric_response(asym_measures, "hOSB", pprint = F)
plist_stressor <- plot_asymmetric_response(asym_measures, "stressor", pprint = F)

textsize <- 10

fig5a <- plist_h0SB[[5]] + 
  labs(x = expression(h[O]), y = expression(Total~shift~magnitude~"["*log[10](μM)*"]"), color = "Magnitude") + 
  scale_y_continuous(limits = c(55, 115), breaks = seq(55, 115, by = 10)) +
  theme_bw() +
  theme(text = element_text(size = textsize),
        axis.title.x = element_blank(),
        axis.text.x= element_blank(),
        legend.title = element_blank(),
        legend.position = "none",
        plot.title = element_blank())

fig5b <- plist_stressor[[5]] + labs(x = "Stressor asymmetry factor", y = "Shift magnitude", color = "Direction") +
 scale_y_continuous(limits = c(55, 115), breaks = seq(55, 115, by = 10)) +
  theme_bw() +
  theme(text = element_text(size = textsize), 
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.title =  element_text(),
        legend.position = c(0.78, 0.82),
        legend.direction = 'vertical', 
        plot.title = element_blank())

fig5c <- plist_h0SB[[4]] + 
  labs(x = expression(H[O]), y = expression(Tipping~point~change~"["*log[10](hr^-1)*"]")) + 
  scale_y_continuous(limits = c(-0.3, 0.1), breaks = c(-0.3, -0.2, -0.1, 0, 0.1)) +
  theme_bw() +
  theme(text = element_text(size = textsize),
        legend.title = element_blank(),
        legend.position = "none",
        plot.title = element_blank())

fig5d <- plist_stressor[[4]] + labs(x = "Stressor asymmetry factor", y = "Tipping point adaption", color = "Direction") +
  scale_y_continuous(breaks = c(-0.3, -0.2, -0.1, 0, 0.1)) +
  theme_bw() +
  theme(text = element_text(size = textsize),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.title =  element_text(),
        legend.position = c(0.78, 0.22),
        legend.direction = 'vertical', 
        plot.title = element_blank())

wrap_plots(fig5a, fig5b, fig5c, fig5d) +
  plot_layout(ncol = 2) +
  plot_annotation(tag_levels = "a") 
  # theme_bw() &
  # theme(legend.title =  element_blank(),
  #   legend.position = "bottom",
  #   legend.direction = 'horizontal', 
  #   title = element_blank())
  
```

